apiVersion: v1
kind: Service
metadata:
  name: {{ include "litemaas.frontend.fullname" . }}
  labels:
    {{- include "litemaas.componentLabels" (dict "context" . "component" "web") | nindent 4 }}
spec:
  selector:
    {{- include "litemaas.componentSelectorLabels" (dict "context" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
