{{- if and (eq .Values.oauth.mode "serviceaccount") (not .Values.oauth.existingTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litemaas.oauth.tokenSecretName" . }}
  labels:
    {{- include "litemaas.componentLabels" (dict "context" . "component" "oauth") | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "litemaas.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
