{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litemaas.postgresql.fullname" . }}
  labels:
    {{- include "litemaas.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
