{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litemaas.serviceAccountName" . }}
  labels:
    {{- include "litemaas.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if .Values.serviceAccount.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.annotations }}
  {{- end }}
  {{- if and (eq .Values.global.platform "openshift") (eq .Values.oauth.mode "serviceaccount") }}
  {{- $callbackUrl := include "litemaas.backend.oauthCallbackUrl" . }}
  {{- if $callbackUrl }}
  {{- $_ := set $annotations "serviceaccounts.openshift.io/oauth-redirecturi.litemaas" $callbackUrl }}
  {{- end }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
